CREATE TABLE companies (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(255) NOT NULL,
    logo_url TEXT,
    website_url TEXT,
    description TEXT,
    industry VARCHAR(255),
    size_category VARCHAR(50),
    location VARCHAR(255),
    city VARCHAR(255),
    state VARCHAR(50),
    country VARCHAR(100) DEFAULT 'United States',
    h1b_sponsor_status VARCHAR(50) DEFAULT 'unknown',
    total_h1b_petitions INTEGER DEFAULT 0,
    total_h1b_approvals INTEGER DEFAULT 0,
    approval_rate DECIMAL(5,2),
    last_h1b_filing_year INTEGER,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);