CREATE TABLE jobs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title VARCHAR(255) NOT NULL,
    company_id UUID,
    company_name VARCHAR(255) NOT NULL,
    description TEXT,
    requirements TEXT,
    salary_min INTEGER,
    salary_max INTEGER,
    salary_currency VARCHAR(10) DEFAULT 'USD',
    location VARCHAR(255),
    city VARCHAR(255),
    state VARCHAR(50),
    country VARCHAR(100) DEFAULT 'United States',
    remote_friendly BOOLEAN DEFAULT false,
    h1b_sponsorship_available BOOLEAN DEFAULT false,
    h1b_sponsorship_confidence DECIMAL(3,2),
    experience_level VARCHAR(50),
    job_type VARCHAR(50) DEFAULT 'full-time',
    industry VARCHAR(255),
    source_url TEXT,
    posted_date TIMESTAMP WITH TIME ZONE,
    expires_date TIMESTAMP WITH TIME ZONE,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);